name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

#------------------------- Packages --------------------------
dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.11

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  
  #state management
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0

#------------------------- Packages END --------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
